Repository DecodersCommunity/College-Notes, pull requests merged in 2022-10, with the labels that each got.

#138 Devansh-200101028
  02.Second-Year-Notes/BiochemicalEngineering/CET-Thermodynamics-Devansh.pdf
Labels: hacktoberfest-accepted

#131 PriyanshiDhanuka-210104040
  01.First-Year-Notes/Physics/Physics-Assignment5-PriyanshiDhanuka.pdf
Labels: Hacktoberfest, hacktoberfest-accepted

#150 200112031
  03.Third-Year-Notes/PaintTechnology/ed2.pdf
Labels: hacktoberfest-accepted

#151 Add files via upload
  03.Third-Year-Notes/PaintTechnology/ed4.pdf
Labels: hacktoberfest-accepted

#148 Shreya Verma-210104050
  01.First-Year-Notes/Mathematics-2/maths unit 1... 2 sem.pdf
Labels: Hacktoberfest, hacktoberfest-accepted

#155 Final CSE Syllabus
  04.Final-Year-Notes/ComputerScience&InformationTechnology/Syllabus.pdf
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#153 ShiwaniKumari-210104049
  01.First-Year-Notes/Mathematics-2/mathematics2 -assignment1-Shiwanikummari.pdf
Labels: Hacktoberfest, hacktoberfest-accepted

#156 Mobile Application Development Notes
  04.Final-Year-Notes/ComputerScience&InformationTechnology/MAD_UNIT I.pdf
  04.Final-Year-Notes/ComputerScience&InformationTechnology/MAD_UNIT II.pdf
Labels: Hacktoberfest, hacktoberfest-accepted

#145 PratibhaSingh-210104039
  01.First-Year-Notes/Engineering-Mechanics/mechanics-theory of tortion-PratibhaSingh.pdf
  01.First-Year-Notes/Physics/physics-electromagnetic-pratibha singh.pdf
Labels: Hacktoberfest, hacktoberfest-accepted

#129 Deepak Sharma - 210108023
  01.First-Year-Notes/Engineering-Chemistry/Chemistry-Namereactions-DeepakSharma.pdf
Labels: Hacktoberfest, hacktoberfest-accepted

#127 Added CCP Unit 5 notes
  01.First-Year-Notes/C-Programming/unit 5 ccp.pdf
  01.First-Year-Notes/C-Programming/unit 5 contd ccp.pdf
Labels: Hacktoberfest, hacktoberfest-accepted

#142 Added Surface Development in Graphics in First Year
  01.First-Year-Notes/Engineering-Graphics/development of surface (1).pdf
Labels: Hacktoberfest, hacktoberfest-accepted

#140 added python chapter one
  02.Second-Year-Notes/ComputerScience&InformationTechnology/PYTHON/python chapter one
Labels: Hacktoberfest, hacktoberfest-accepted

#159 Added binary tree
  03.Third-Year-Notes/ComputerScience&InformationTechnology/B-Tree(UNIT-2)'By Achintya Pandey.pdf
Labels: hacktoberfest-accepted

#161 added notes
  02.Second-Year-Notes/Functions In Python.pdf
  02.Second-Year-Notes/Python Unit-2 Detailed Notes.pdf
  03.Third-Year-Notes/ComputerScience&InformationTechnology/7)+Time+Series.pdf
Labels: hacktoberfest-accepted
